# Generated by Django 4.1.13 on 2026-03-15 07:41

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('club_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='社团ID')),
                ('name', models.CharField(max_length=100, verbose_name='社团名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='社团简介')),
                ('established_date', models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='成立日期')),
                ('president', models.CharField(blank=True, max_length=30, null=True, verbose_name='社长姓名')),
                ('contact_phone', models.CharField(blank=True, max_length=11, null=True, verbose_name='联系电话')),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='联系邮箱')),
                ('status', models.SmallIntegerField(choices=[(1, '正常'), (2, '暂停'), (3, '解散')], default=1, verbose_name='状态')),
                ('create_time', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '社团',
                'db_table': '社团表',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='部门ID')),
                ('name', models.CharField(max_length=100, verbose_name='部门名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='部门简介')),
                ('create_time', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='创建时间')),
                ('club', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='app01.club', verbose_name='所属社团')),
            ],
            options={
                'verbose_name': '部门',
                'db_table': '部门表',
            },
        ),
        migrations.CreateModel(
            name='MyAdmin',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='管理员账号')),
                ('user_name', models.CharField(max_length=32, verbose_name='管理员名')),
                ('password', models.CharField(max_length=64, verbose_name='管理员密码')),
            ],
            options={
                'verbose_name': '管理员',
                'db_table': '管理员表',
            },
        ),
        migrations.CreateModel(
            name='Recruitment',
            fields=[
                ('recruitment_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='招新ID')),
                ('title', models.CharField(max_length=100, verbose_name='批次名称')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='开始日期')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='结束日期')),
                ('status', models.SmallIntegerField(choices=[(1, '报名中'), (2, '已结束')], default=1, verbose_name='状态')),
                ('create_time', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='创建时间')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recruitments', to='app01.club', verbose_name='所属社团')),
            ],
            options={
                'verbose_name': '招新批次',
                'db_table': '招新批次表',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('role_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='角色ID')),
                ('name', models.CharField(max_length=50, verbose_name='角色名称')),
                ('level', models.SmallIntegerField(choices=[(1, '社长'), (2, '普通成员')], default=2, verbose_name='级别')),
                ('description', models.TextField(blank=True, null=True, verbose_name='角色描述')),
            ],
            options={
                'verbose_name': '角色',
                'db_table': '角色表',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('member_id', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='学号')),
                ('name', models.CharField(max_length=30, verbose_name='姓名')),
                ('gender', models.SmallIntegerField(blank=True, choices=[(1, '男'), (2, '女')], null=True, verbose_name='性别')),
                ('grade', models.SmallIntegerField(blank=True, choices=[(1, '大一'), (2, '大二'), (3, '大三'), (4, '大四'), (5, '研究生')], null=True, verbose_name='年级')),
                ('major', models.CharField(blank=True, max_length=100, null=True, verbose_name='专业')),
                ('phone', models.CharField(blank=True, max_length=11, null=True, verbose_name='手机号')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='邮箱')),
                ('join_time', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='加入时间')),
                ('status', models.SmallIntegerField(choices=[(1, '正常'), (2, '请假'), (3, '退社')], default=1, verbose_name='状态')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('password', models.CharField(blank=True, max_length=64, null=True, verbose_name='登录密码')),
                ('club', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='app01.club', verbose_name='所属社团')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='app01.department', verbose_name='所属部门')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='app01.role', verbose_name='角色')),
            ],
            options={
                'verbose_name': '成员',
                'db_table': '成员表',
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('activity_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='活动ID')),
                ('title', models.CharField(max_length=100, verbose_name='活动名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='活动描述')),
                ('location', models.CharField(blank=True, max_length=200, null=True, verbose_name='活动地点')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('max_participants', models.IntegerField(blank=True, default=0, null=True, verbose_name='最大参与人数')),
                ('current_participants', models.IntegerField(default=0, verbose_name='当前参与人数')),
                ('status', models.SmallIntegerField(choices=[(1, '报名中'), (2, '进行中'), (3, '已结束'), (4, '已取消')], default=1, verbose_name='状态')),
                ('create_time', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='创建时间')),
                ('club', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='app01.club', verbose_name='所属社团')),
                ('organizer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organized_activities', to='app01.member', verbose_name='组织者')),
            ],
            options={
                'verbose_name': '活动',
                'db_table': '活动表',
            },
        ),
        migrations.CreateModel(
            name='RecruitmentApplication',
            fields=[
                ('application_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='报名ID')),
                ('student_id', models.CharField(max_length=30, verbose_name='学号')),
                ('name', models.CharField(max_length=30, verbose_name='姓名')),
                ('gender', models.SmallIntegerField(blank=True, choices=[(1, '男'), (2, '女')], null=True, verbose_name='性别')),
                ('grade', models.SmallIntegerField(blank=True, choices=[(1, '大一'), (2, '大二'), (3, '大三'), (4, '大四'), (5, '研究生')], null=True, verbose_name='年级')),
                ('major', models.CharField(blank=True, max_length=100, null=True, verbose_name='专业')),
                ('phone', models.CharField(blank=True, max_length=11, null=True, verbose_name='手机号')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='邮箱')),
                ('status', models.SmallIntegerField(choices=[(1, '待审核'), (2, '已通过'), (3, '已拒绝')], default=1, verbose_name='状态')),
                ('apply_time', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='申请时间')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('apply_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recruitment_applications', to='app01.department', verbose_name='申请部门')),
                ('recruitment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='app01.recruitment', verbose_name='招新批次')),
            ],
            options={
                'verbose_name': '招新报名',
                'db_table': '招新报名表',
                'unique_together': {('recruitment', 'student_id')},
            },
        ),
        migrations.CreateModel(
            name='ActivityRegistration',
            fields=[
                ('registration_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='报名ID')),
                ('register_time', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='报名时间')),
                ('status', models.SmallIntegerField(choices=[(1, '已报名'), (2, '已参加'), (3, '已取消'), (4, '未参加')], default=1, verbose_name='状态')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='app01.activity', verbose_name='活动')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='app01.member', verbose_name='成员')),
            ],
            options={
                'verbose_name': '活动报名',
                'db_table': '活动报名表',
                'unique_together': {('activity', 'member')},
            },
        ),
    ]
