# Generated by Django 4.1.13 on 2026-03-15 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_create_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='app01.club', verbose_name='所属社团'),
        ),
    ]
