# Generated by Django 4.1.13 on 2026-04-05 13:26

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_announcement_club'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='头像'),
        ),
        migrations.AddField(
            model_name='member',
            name='nickname',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='昵称'),
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('follow_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='关注ID')),
                ('follow_time', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='关注时间')),
                ('followed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='app01.member', verbose_name='被关注者')),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to='app01.member', verbose_name='关注者')),
            ],
            options={
                'verbose_name': '关注',
                'db_table': 'follow',
                'unique_together': {('follower', 'followed')},
            },
        ),
    ]
