# Generated by Django 4.1.13 on 2026-04-05 14:43

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0006_member_avatar_member_nickname_follow'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityPhoto',
            fields=[
                ('photo_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='照片ID')),
                ('photo', models.ImageField(upload_to='activity_photos/', verbose_name='照片')),
                ('description', models.TextField(blank=True, null=True, verbose_name='照片描述')),
                ('upload_time', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='上传时间')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='app01.activity', verbose_name='活动')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_photos', to='app01.member', verbose_name='上传者')),
            ],
            options={
                'verbose_name': '活动照片',
                'db_table': 'activity_photo',
                'ordering': ['-upload_time'],
            },
        ),
        migrations.CreateModel(
            name='ActivityComment',
            fields=[
                ('comment_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='评论ID')),
                ('content', models.TextField(verbose_name='评论内容')),
                ('create_time', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='评论时间')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='app01.activity', verbose_name='活动')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_comments', to='app01.member', verbose_name='评论者')),
            ],
            options={
                'verbose_name': '活动评论',
                'db_table': 'activity_comment',
                'ordering': ['create_time'],
            },
        ),
        migrations.CreateModel(
            name='ActivityLike',
            fields=[
                ('like_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='点赞ID')),
                ('like_time', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='点赞时间')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='app01.activity', verbose_name='活动')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_likes', to='app01.member', verbose_name='点赞者')),
            ],
            options={
                'verbose_name': '活动点赞',
                'db_table': 'activity_like',
                'unique_together': {('activity', 'member')},
            },
        ),
    ]
