# Generated by Django 4.1.13 on 2026-04-21 08:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0007_activityphoto_activitycomment_activitylike'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubDiscussion',
            fields=[
                ('discussion_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='讨论ID')),
                ('content', models.TextField(verbose_name='讨论内容')),
                ('create_time', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='发言时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discussions', to='app01.club', verbose_name='所属社团')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discussions', to='app01.member', verbose_name='发言者')),
            ],
            options={
                'verbose_name': '社团讨论',
                'db_table': 'club_discussion',
                'ordering': ['-create_time'],
            },
        ),
    ]
