# Generated by Django 4.1.13 on 2026-04-21 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0008_clubdiscussion'),
    ]

    operations = [
        migrations.AddField(
            model_name='myadmin',
            name='account',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True, verbose_name='登录账号'),
        ),
        migrations.AlterField(
            model_name='myadmin',
            name='id',
            field=models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
