# Generated by Django 4.2 on 2025-12-07 11:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0009_alter_userinfo_creat_time_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='creat_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 12, 7, 19, 40, 12, 577201), null=True, verbose_name='入职时间'),
        ),
    ]
