# Generated by Django 4.1.13 on 2026-04-25 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0009_myadmin_account_alter_myadmin_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='status',
        ),
    ]
