# Generated by Django 4.1 on 2025-12-07 11:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0010_alter_userinfo_creat_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='creat_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 12, 7, 19, 42, 46, 244070), null=True, verbose_name='入职时间'),
        ),
    ]
