# Generated by Django 4.1.13 on 2026-04-25 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0010_remove_club_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='status',
        ),
    ]
