# Generated by Django 4.1.13 on 2026-04-25 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0011_remove_member_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='description',
        ),
    ]
