# Generated by Django 4.1 on 2025-12-07 12:55

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0011_alter_userinfo_creat_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('activity_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='活动ID')),
                ('title', models.CharField(max_length=100, verbose_name='活动名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='活动描述')),
                ('location', models.CharField(blank=True, max_length=200, null=True, verbose_name='活动地点')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('max_participants', models.IntegerField(blank=True, default=0, null=True, verbose_name='最大参与人数')),
                ('current_participants', models.IntegerField(default=0, verbose_name='当前参与人数')),
                ('status', models.SmallIntegerField(choices=[(1, '报名中'), (2, '进行中'), (3, '已结束'), (4, '已取消')], default=1, verbose_name='状态')),
                ('create_time', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '活动',
                'db_table': '活动表',
            },
        ),
        migrations.CreateModel(
            name='ActivityRegistration',
            fields=[
                ('registration_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='报名ID')),
                ('register_time', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='报名时间')),
                ('status', models.SmallIntegerField(choices=[(1, '已报名'), (2, '已参加'), (3, '已取消'), (4, '未参加')], default=1, verbose_name='状态')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='app01.activity', verbose_name='活动')),
            ],
            options={
                'verbose_name': '活动报名',
                'db_table': '活动报名表',
            },
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('club_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='社团ID')),
                ('name', models.CharField(max_length=100, verbose_name='社团名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='社团简介')),
                ('established_date', models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='成立日期')),
                ('president', models.CharField(blank=True, max_length=30, null=True, verbose_name='社长姓名')),
                ('contact_phone', models.CharField(blank=True, max_length=11, null=True, verbose_name='联系电话')),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='联系邮箱')),
                ('status', models.SmallIntegerField(choices=[(1, '正常'), (2, '暂停'), (3, '解散')], default=1, verbose_name='状态')),
                ('create_time', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '社团',
                'db_table': '社团表',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('member_id', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='学号')),
                ('name', models.CharField(max_length=30, verbose_name='姓名')),
                ('gender', models.SmallIntegerField(blank=True, choices=[(1, '男'), (2, '女')], null=True, verbose_name='性别')),
                ('grade', models.SmallIntegerField(blank=True, choices=[(1, '大一'), (2, '大二'), (3, '大三'), (4, '大四'), (5, '研究生')], null=True, verbose_name='年级')),
                ('major', models.CharField(blank=True, max_length=100, null=True, verbose_name='专业')),
                ('phone', models.CharField(blank=True, max_length=11, null=True, verbose_name='手机号')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='邮箱')),
                ('join_time', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='加入时间')),
                ('status', models.SmallIntegerField(choices=[(1, '正常'), (2, '请假'), (3, '退社')], default=1, verbose_name='状态')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('club', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='app01.club', verbose_name='所属社团')),
            ],
            options={
                'verbose_name': '成员',
                'db_table': '成员表',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('role_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='角色ID')),
                ('name', models.CharField(max_length=50, verbose_name='角色名称')),
                ('level', models.SmallIntegerField(choices=[(1, '社长'), (2, '副社长'), (3, '部长'), (4, '副部长'), (5, '普通成员')], default=5, verbose_name='级别')),
                ('description', models.TextField(blank=True, null=True, verbose_name='角色描述')),
            ],
            options={
                'verbose_name': '角色',
                'db_table': '角色表',
            },
        ),
        migrations.RemoveField(
            model_name='order',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.DeleteModel(
            name='PhoneNumbers',
        ),
        migrations.RemoveField(
            model_name='task',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='department',
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name': '部门'},
        ),
        migrations.RemoveField(
            model_name='department',
            name='title',
        ),
        migrations.AddField(
            model_name='department',
            name='create_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='department',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='部门简介'),
        ),
        migrations.AddField(
            model_name='department',
            name='name',
            field=models.CharField(default='默认部门', max_length=100, verbose_name='部门名称'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='department',
            name='department_id',
            field=models.BigAutoField(primary_key=True, serialize=False, verbose_name='部门ID'),
        ),
        migrations.AlterModelTable(
            name='department',
            table='部门表',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
        migrations.DeleteModel(
            name='UserInfo',
        ),
        migrations.AddField(
            model_name='member',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='app01.department', verbose_name='所属部门'),
        ),
        migrations.AddField(
            model_name='member',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='app01.role', verbose_name='角色'),
        ),
        migrations.AddField(
            model_name='activityregistration',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='app01.member', verbose_name='成员'),
        ),
        migrations.AddField(
            model_name='activity',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='app01.club', verbose_name='所属社团'),
        ),
        migrations.AddField(
            model_name='activity',
            name='organizer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organized_activities', to='app01.member', verbose_name='组织者'),
        ),
        migrations.AddField(
            model_name='department',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='app01.club', verbose_name='所属社团'),
        ),
        migrations.AlterUniqueTogether(
            name='activityregistration',
            unique_together={('activity', 'member')},
        ),
    ]
