# Generated by Django 4.1.13 on 2026-04-25 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0012_remove_role_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='remark',
        ),
    ]
