# Generated by Django 4.1 on 2026-03-15 06:30

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0012_activity_activityregistration_club_member_role_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recruitment',
            fields=[
                ('recruitment_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='招新ID')),
                ('title', models.CharField(max_length=100, verbose_name='批次名称')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='开始日期')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='结束日期')),
                ('status', models.SmallIntegerField(choices=[(1, '报名中'), (2, '已结束')], default=1, verbose_name='状态')),
                ('create_time', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='创建时间')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recruitments', to='app01.club', verbose_name='所属社团')),
            ],
            options={
                'verbose_name': '招新批次',
                'db_table': '招新批次表',
            },
        ),
        migrations.CreateModel(
            name='RecruitmentApplication',
            fields=[
                ('application_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='报名ID')),
                ('student_id', models.CharField(max_length=30, verbose_name='学号')),
                ('name', models.CharField(max_length=30, verbose_name='姓名')),
                ('gender', models.SmallIntegerField(blank=True, choices=[(1, '男'), (2, '女')], null=True, verbose_name='性别')),
                ('grade', models.SmallIntegerField(blank=True, choices=[(1, '大一'), (2, '大二'), (3, '大三'), (4, '大四'), (5, '研究生')], null=True, verbose_name='年级')),
                ('major', models.CharField(blank=True, max_length=100, null=True, verbose_name='专业')),
                ('phone', models.CharField(blank=True, max_length=11, null=True, verbose_name='手机号')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='邮箱')),
                ('status', models.SmallIntegerField(choices=[(1, '待审核'), (2, '已通过'), (3, '已拒绝')], default=1, verbose_name='状态')),
                ('apply_time', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='申请时间')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('apply_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recruitment_applications', to='app01.department', verbose_name='申请部门')),
                ('recruitment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='app01.recruitment', verbose_name='招新批次')),
            ],
            options={
                'verbose_name': '招新报名',
                'db_table': '招新报名表',
                'unique_together': {('recruitment', 'student_id')},
            },
        ),
    ]
