# Generated by Django 4.1.13 on 2026-04-25 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0013_remove_member_remark'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activityregistration',
            name='register_time',
        ),
        migrations.RemoveField(
            model_name='activityregistration',
            name='remark',
        ),
    ]
