# Generated by Django 4.1 on 2026-03-15 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0013_recruitment'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='password',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='登录密码'),
        ),
    ]
