# Generated by Django 4.1.13 on 2026-04-25 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0014_remove_registration_register_time_and_remark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='status',
            field=models.SmallIntegerField(choices=[(1, '发布'), (2, '草稿')], default=1, verbose_name='状态'),
        ),
    ]
