# Generated by Django 4.1 on 2026-03-15 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0015_member_default_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='level',
            field=models.SmallIntegerField(choices=[(1, '社长'), (2, '普通成员')], default=2, verbose_name='级别'),
        ),
    ]
