# Generated by Django 4.1.13 on 2026-04-28 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0015_remove_announcement_delete_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='publisher_name',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='发布者姓名'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='publisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements', to='app01.myadmin', verbose_name='发布者(管理员)'),
        ),
    ]
