# Generated by Django 4.1.13 on 2026-05-25 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0016_add_publisher_name_to_announcement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='president',
        ),
        migrations.AddField(
            model_name='club',
            name='president_id',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='社长学号'),
        ),
    ]
